### PR TITLE
[Release] 0.1.0 and 0.2.0

### PR DESCRIPTION
**Pull request by manh-t**
## What happened 👀

☝️ 

## Proof Of Work 📹

n/a

### CODE REVIEW

**Review by luongvo — COMMENTED** [review]
@manh-t the `main` and `master` are conflicting together, it seems you're using main branch as a `develop`. I think we should rename `main` to `develop` and then do release into `master` or new `main` branch.

**Comment by manh-t** [comment]
@luongvo yes I forgot to rename `main` to `develop` so I'm using it as `develop` branch 😢  I don't know how the PRs affect when I rename `main` to `develop`, I'll check it 🙏

**Review by luongvo — APPROVED** [review]

**Comment by manh-t** [comment]
thankfully I don't meet any problems when renaming `main` -> `develop` 😆 
@luongvo now I use `develop` branch for development and `master` branch for release, thanks a lot 🤗

**Comment by luongvo** [comment]
@manh-t you can release it now, let's speed up your IC development

**Pull request merged**
